// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/12/2026, 2:01:10 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/VICTUS/agazi-school-system/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/VICTUS/agazi-school-system/frontend/composables/**/*.{js,ts,mjs}","C:/Users/VICTUS/agazi-school-system/frontend/utils/**/*.{js,ts,mjs}","C:/Users/VICTUS/agazi-school-system/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VICTUS/agazi-school-system/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;