import type { Mall, Building, Shop, Product } from "./types"

export const malls: Mall[] = [
  {
    _id: "mall1",
    name: "Edna Mall",
    location: "Bole Road",
    city: "Addis Ababa",
    description: "One of the largest shopping malls in Addis Ababa",
    googleMapsUrl: "https://maps.google.com/?q=Edna+Mall+Addis+Ababa",
    createdAt: new Date("2015-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "mall2",
    name: "Century Mall Gurd Shola",
    location: "Gurd Shola",
    city: "Addis Ababa",
    description: "Modern shopping complex in Gurd Shola area",
    googleMapsUrl: "https://maps.google.com/?q=Century+Mall+Gurd+Shola+Addis+Ababa",
    createdAt: new Date("2018-03-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "mall3",
    name: "Ambassador Mall",
    location: "Kazanchis",
    city: "Addis Ababa",
    description: "Premium shopping destination in Kazanchis",
    googleMapsUrl: "https://maps.google.com/?q=Ambassador+Mall+Kazanchis+Addis+Ababa",
    createdAt: new Date("2016-06-20"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "mall4",
    name: "Lideta Market Mall",
    location: "Lideta",
    city: "Addis Ababa",
    description: "Popular market mall in Lideta area",
    googleMapsUrl: "https://maps.google.com/?q=Lideta+Market+Mall+Addis+Ababa",
    createdAt: new Date("2017-09-10"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "mall5",
    name: "Morning Star Mall",
    location: "Bole",
    city: "Addis Ababa",
    description: "Shopping center in the heart of Bole",
    googleMapsUrl: "https://maps.google.com/?q=Morning+Star+Mall+Bole+Addis+Ababa",
    createdAt: new Date("2019-02-15"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const buildings: Building[] = [
  {
    _id: "building1",
    mallId: "mall1",
    name: "Main Building",
    floor: "Ground - 4th Floor",
    description: "Primary shopping area",
    createdAt: new Date("2015-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "building2",
    mallId: "mall2",
    name: "East Wing",
    floor: "Ground - 3rd Floor",
    description: "Fashion and electronics",
    createdAt: new Date("2018-03-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "building3",
    mallId: "mall3",
    name: "Central Block",
    floor: "Ground - 5th Floor",
    description: "All retail categories",
    createdAt: new Date("2016-06-20"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "building4",
    mallId: "mall4",
    name: "Market Section",
    floor: "Ground - 2nd Floor",
    description: "Traditional and modern shops",
    createdAt: new Date("2017-09-10"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "building5",
    mallId: "mall5",
    name: "North Tower",
    floor: "Ground - 3rd Floor",
    description: "Specialty stores",
    createdAt: new Date("2019-02-15"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const shops: Shop[] = [
  {
    _id: "shop1",
    buildingId: "building1",
    name: "TechZone Electronics",
    category: "Electronics",
    floor: "2nd Floor",
    unit: "N-201",
    description: "Latest gadgets and electronics",
    phoneNumber: "+251 11 123 4567",
    googleMapsUrl: "https://maps.google.com/?q=TechZone+Electronics+Edna+Mall",
    createdAt: new Date("2020-02-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "shop2",
    buildingId: "building1",
    name: "Fashion Forward",
    category: "Clothing",
    floor: "1st Floor",
    unit: "N-105",
    description: "Trendy fashion for all ages",
    phoneNumber: "+251 11 234 5678",
    googleMapsUrl: "https://maps.google.com/?q=Fashion+Forward+Edna+Mall",
    createdAt: new Date("2020-02-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "shop3",
    buildingId: "building2",
    name: "Home Essentials",
    category: "Home & Living",
    floor: "Ground Floor",
    unit: "S-G12",
    description: "Everything for your home",
    phoneNumber: "+251 11 345 6789",
    googleMapsUrl: "https://maps.google.com/?q=Home+Essentials+Century+Mall",
    createdAt: new Date("2020-02-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "shop4",
    buildingId: "building3",
    name: "Sports Arena",
    category: "Sports",
    floor: "3rd Floor",
    unit: "M-305",
    description: "Sports equipment and apparel",
    phoneNumber: "+251 11 456 7890",
    googleMapsUrl: "https://maps.google.com/?q=Sports+Arena+Ambassador+Mall",
    createdAt: new Date("2021-04-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "shop5",
    buildingId: "building3",
    name: "Book Haven",
    category: "Books",
    floor: "2nd Floor",
    unit: "M-210",
    description: "Wide selection of books and magazines",
    phoneNumber: "+251 11 567 8901",
    googleMapsUrl: "https://maps.google.com/?q=Book+Haven+Ambassador+Mall",
    createdAt: new Date("2021-04-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "shop6",
    buildingId: "building4",
    name: "Beauty Boutique",
    category: "Beauty",
    floor: "1st Floor",
    unit: "E-115",
    description: "Cosmetics and skincare products",
    phoneNumber: "+251 11 678 9012",
    googleMapsUrl: "https://maps.google.com/?q=Beauty+Boutique+Lideta+Market+Mall",
    createdAt: new Date("2019-07-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "shop7",
    buildingId: "building1",
    name: "Mobile World",
    category: "Electronics",
    floor: "2nd Floor",
    unit: "N-215",
    description: "Smartphones and accessories",
    phoneNumber: "+251 11 789 0123",
    googleMapsUrl: "https://maps.google.com/?q=Mobile+World+Edna+Mall",
    createdAt: new Date("2020-03-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const products: Product[] = [
  {
    _id: "prod1",
    shopId: "shop1",
    name: "Wireless Headphones Pro",
    category: "Audio",
    price: 10999,
    description: "Premium noise-cancelling headphones",
    inStock: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    _id: "prod2",
    shopId: "shop1",
    name: "Smart Watch Series 5",
    category: "Wearables",
    price: 21999,
    description: "Advanced fitness and health tracking",
    inStock: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    _id: "prod3",
    shopId: "shop1",
    name: "Laptop Stand Aluminum",
    category: "Accessories",
    price: 2749,
    description: "Ergonomic laptop stand",
    inStock: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    _id: "prod4",
    shopId: "shop2",
    name: "Designer Jeans",
    category: "Clothing",
    price: 4949,
    description: "Premium denim jeans",
    inStock: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    _id: "prod5",
    shopId: "shop2",
    name: "Leather Jacket",
    category: "Clothing",
    price: 13749,
    description: "Genuine leather jacket",
    inStock: false,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    _id: "prod6",
    shopId: "shop3",
    name: "Coffee Maker Deluxe",
    category: "Kitchen",
    price: 7149,
    description: "Programmable coffee maker",
    inStock: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    _id: "prod7",
    shopId: "shop3",
    name: "Bedding Set Queen",
    category: "Bedroom",
    price: 4399,
    description: "Luxury cotton bedding set",
    inStock: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    _id: "prod8",
    shopId: "shop4",
    name: "Yoga Mat Premium",
    category: "Fitness",
    price: 2199,
    description: "Non-slip yoga mat",
    inStock: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    _id: "prod9",
    shopId: "shop4",
    name: "Running Shoes Pro",
    category: "Footwear",
    price: 8249,
    description: "Professional running shoes",
    inStock: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    _id: "prod10",
    shopId: "shop5",
    name: "The Great Novel",
    category: "Fiction",
    price: 1374,
    description: "Bestselling fiction novel",
    inStock: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    _id: "prod11",
    shopId: "shop5",
    name: "Cookbook Collection",
    category: "Cooking",
    price: 1924,
    description: "Complete cookbook series",
    inStock: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    _id: "prod12",
    shopId: "shop6",
    name: "Skincare Set",
    category: "Skincare",
    price: 4949,
    description: "Complete skincare routine",
    inStock: true,
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    _id: "prod13",
    shopId: "shop6",
    name: "Makeup Palette Pro",
    category: "Makeup",
    price: 3299,
    description: "Professional makeup palette",
    inStock: true,
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    _id: "prod14",
    shopId: "shop7",
    name: "Smartphone Case Premium",
    category: "Accessories",
    price: 1649,
    description: "Protective phone case",
    inStock: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    _id: "prod15",
    shopId: "shop7",
    name: "Wireless Charger Fast",
    category: "Accessories",
    price: 2199,
    description: "Fast wireless charging pad",
    inStock: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
]
